#!/bin/bash

CHECK_TOOL=check-env

BIG="figlet -k -w 0.1 "
COLOR="lolcat --spread 1.0 --animate --speed 100.0"

hi(){
    clear
    echo "Welcom to TAO-ECO" | $BIG | $COLOR
    echo "This environment is for dataset and inference via TensorRT" | $COLOR
    echo -e "\nYou Can Check System's Info via '${CHECK_TOOL}'\n" | $COLOR
}

hi_ds(){
    clear
    echo "Welcom to TAO-ECO" | $BIG | $COLOR
    echo "This environment is for deep stream" | $COLOR
    echo -e "\nYou Can Check System's Info via '${CHECK_TOOL}'\n" | $COLOR
}

option=$1

case $option in
    eco) # display Help
        hi
        exit;;
    deepstream)
        hi_ds
        exit;;
esac